# Generated by Django 5.0.1 on 2024-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_abc_cde'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='reviewType',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
