# Generated by Django 5.0.1 on 2024-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating_reviewtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='reviewType',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
